name: myassistantv2
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.5.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  dotted_border: ^1.0.5
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.5.3+4
  http:
  fluttertoast:
  page_transition:
  flutter_facebook_login: ^3.0.0
  firebase_auth: ^0.16.1
  flutter_datetime_picker: ^1.3.8
  theme_provider: ^0.3.2
  google_sign_in: ^4.1.4
  local_auth: ^0.6.1+3
  flutter_launcher_icons: ^0.7.5
  devicelocale: ^0.2.2
  date_util: ^0.1.4
  date_picker_timeline: ^1.2.0
  provider: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - lang/language.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/myassistant-logo.png"
